services:
  app:
    build: .
    ports:
      - "3000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/linkday
      - JWT_SECRET=${JWT_SECRET:-your-super-secret-jwt-key-change-this-in-production}
    depends_on:
      - mongodb
    networks:
      - linkday-network
    restart: unless-stopped

  mongodb:
    image: mongo:7.0-jammy
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=linkday
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - linkday-network
    restart: unless-stopped

volumes:
  mongodb_data:

networks:
  linkday-network:
    driver: bridge